/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Brandon Westlake (https://sketchfab.com/dr.badass2142)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/958136efb5bc48c6b1bf20dd444a4b84
title: Simple Desk (FREE)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('desk.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry}  >
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/desk.gltf')
